export const APP_NAME = 'E-TICKETING';
export const AUTHNZ_SERVICE = 'AUTHNZ_SERVICE';
export const BOOKING_SERVICE = 'BOOKING_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const REGISTER_SERVICE = 'REGISTER_SERVICE';
