services:
  db:
    image: postgres:14-bookworm
    environment:
      POSTGRES_USER: savingautomaton
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    image: savingautomaton
    secrets:
      - config.yaml
    build:
      context: ./server
    environment:
      DATABASE_URL: "postgresql://savingautomaton@db/savingautomaton"
    ports:
      - 3000:3000

secrets:
  config.yaml:
    file: ./config.yaml

