# Kubernetes Deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: savings-automaton-db-secret
type: Opaque
data:
  # Base64 encoded PostgreSQL connection string (e.g., echo -n 'postgres://user:pass@host:5432/dbname' | base64)
  DB_DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3NAbG9jYWxob3N0OjU0MzIvbXlkYg== # REPLACE THIS WITH YOUR ACTUAL BASE64 ENCODED DATABASE_URL
---
apiVersion: v1
kind: Secret
metadata:
  name: savings-automaton-configuration
type: Opaque
stringData:
  # Base64 encoded config.yaml
  config.yaml: |
    YXBpOgogIGRvbWFpbjogJ2h0dHA6Ly9sb2NhbGhvc3Q6ODAwMCcKCiMgQVBJIHRvIHdvcmsgd2l0
    aCBFcXVpdHkgQmFuayBBY2NvdW50cwpqZW5nYTogIyBodHRwczovL2RldmVsb3Blci5qZW5nYWhx
    LmlvLwogIGFwaV9iYXNlOiAiaHR0cHM6Ly91YXQuZmluc2VydmUuYWZyaWNhIgogIG1lcmNoYW50
    X2NvZGU6ICcxMjM0NTYnCiAgYXBpX2tleTogInNrX2FwaV9rZXkiCiAgY29uc3VtZXJfc2VjcmV0
    OiAic2tfY29uc3VtZXJfc2VjcmV0IgogIHN0azoKICAgIHB1c2hfdHlwZTogIlVTU0QiCiAgY2Fs
    bGJhY2tfcGF0aDogJy9kYXJhamEnCiAgYmFua19hY2NvdW50OiAjIEJhbmsgRGV0YWlscwogICAg
    bmFtZTogJ3Rlc3RpbmctYWNjb3VudCcKICAgIG51bWJlcjogJzA5ODc2NTQzMjEnCiAgICBjb3Vu
    dHJ5X2NvZGU6ICdLRU4nCgo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-automaton-deployment
  labels:
    app: savings-automaton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savings-automaton
  template:
    metadata:
      labels:
        app: savings-automaton
    spec:
      securityContext:
        privileged: false
        runAsNonRoot: true
        fsGroup: 1000
      volumes:
        - name: secret-volume
          secret:
            secretName: savings-automaton-configuration
      containers:
        - name: savings-automaton
          image: savings-automaton:latest
          ports:
            - containerPort: 3000
              name: http-server
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: savings-automaton-db-secret
                  key: DB_DATABASE_URL
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/run/secrets/savings-automaton"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http-server
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http-server
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: savings-automaton-service
  labels:
    app: savings-automaton
spec:
  selector:
    app: savings-automaton
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
  type: ClusterIP
